spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bosssoft?useUnicode=true&characterEncoding=UTF-8&useSSL=false

---

spring:
  mvc:
    static-path-pattern: /static/**    #静态资源的请求方式
  resources:
    static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录

---
# 配置模板引擎以及视图解析(这个已经被自动配置了，如果想修改可以自己再配置)
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

---
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

---
mybatis:
  configuration:
    map-underscore-to-camel-case: true